import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
} from "@solana/web3.js";
import {
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  getAssociatedTokenAddress,
  getAccount,
} from "@solana/spl-token";
import { AnchorProvider, Program, BN, Wallet } from "@coral-xyz/anchor";
import type { ScheduledTransfer } from "../src/idl/scheduled_transfer";
import IDL from "../src/idl/scheduled_transfer.json";
import * as fs from "fs";
import * as path from "path";

export const PROGRAM_ID = new PublicKey(
  "5BhDb1YqZq8f9yED9rphTobT4zB25cwWWqLaZtYWCJd4",
);

// Devnet mint addresses (must match what the on-chain program expects)
export const USDC_MINT = new PublicKey(
  "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
);
export const USDT_MINT = new PublicKey(
  "EJwZgeZrdC8TXTQbQBoL6bfuAnFUUy1PVCMB4DYPzVaS",
);

const RPC_URL = process.env.INTEGRATION_RPC_URL ?? "http://127.0.0.1:8899";

export function getConnection(): Connection {
  return new Connection(RPC_URL, "confirmed");
}

export function createProgram(
  connection: Connection,
  payer: Keypair,
): Program<ScheduledTransfer> {
  const wallet = new Wallet(payer);
  const provider = new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  return new Program(IDL as ScheduledTransfer, provider);
}

export async function airdrop(
  connection: Connection,
  to: PublicKey,
  sol: number = 10,
): Promise<void> {
  const sig = await connection.requestAirdrop(to, sol * LAMPORTS_PER_SOL);
  await connection.confirmTransaction(sig, "confirmed");
}

/**
 * Create a new SPL token mint controlled by `mintAuthority` and return its address.
 */
export async function createTestMint(
  connection: Connection,
  payer: Keypair,
  mintAuthority: PublicKey,
  decimals: number = 6,
): Promise<PublicKey> {
  return createMint(connection, payer, mintAuthority, null, decimals);
}

/**
 * Create an ATA for `owner` and mint `amount` tokens into it.
 * Returns the ATA address.
 */
export async function createAndFundAta(
  connection: Connection,
  payer: Keypair,
  mint: PublicKey,
  mintAuthority: Keypair,
  owner: PublicKey,
  amount: number | bigint,
): Promise<PublicKey> {
  const { address: ata } = await getOrCreateAssociatedTokenAccount(
    connection,
    payer,
    mint,
    owner,
    true, // allowOwnerOffCurve — needed for PDA owners
  );
  if (amount > 0) {
    await mintTo(connection, payer, mint, ata, mintAuthority, amount);
  }
  return ata;
}

export async function getTokenBalance(
  connection: Connection,
  ata: PublicKey,
): Promise<bigint> {
  const account = await getAccount(connection, ata);
  return account.amount;
}

// PDA derivation helpers (mirrors src/utils/pda.ts but standalone)

export function findScheduleCounterPda(
  authority: PublicKey,
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("schedule_counter"), authority.toBuffer()],
    PROGRAM_ID,
  );
}

export function findPaymentSchedulePda(
  authority: PublicKey,
  scheduleId: bigint | BN,
): [PublicKey, number] {
  const id = typeof scheduleId === "bigint" ? scheduleId : BigInt(scheduleId.toString());
  const idBuf = Buffer.alloc(8);
  idBuf.writeBigUInt64LE(id);
  return PublicKey.findProgramAddressSync(
    [Buffer.from("payment_schedule"), authority.toBuffer(), idBuf],
    PROGRAM_ID,
  );
}

/**
 * Load the mint authority keypair generated by setup-validator.ts.
 */
export function loadMintAuthority(): Keypair {
  const fixturePath = path.join(
    import.meta.dirname!,
    "fixtures",
    "mint-authority.json",
  );
  const raw = JSON.parse(fs.readFileSync(fixturePath, "utf-8"));
  return Keypair.fromSecretKey(Uint8Array.from(raw));
}

export { BN, Keypair, PublicKey, SystemProgram, LAMPORTS_PER_SOL };
export { getAssociatedTokenAddress };
